project_id = "codhlwjogfjywmjyjbbn"

[functions.test-signal-generation]
verify_jwt = false

[functions.simple-test]
verify_jwt = false

[functions.add-testnet-balance]
verify_jwt = false

[functions.live-signals-generator]
verify_jwt = false

[functions.live-price-feed]
verify_jwt = false

[functions.auto-signals-scheduler]
verify_jwt = false

[functions.fetch-all-symbols]
verify_jwt = false

[functions.enable-all-symbols]
verify_jwt = false