project_id = "codhlwjogfjywmjyjbbn"

[functions.aitradex1-strategy-engine]
verify_jwt = false

[functions.aitradex1-comprehensive-engine]
verify_jwt = false

[functions.aitradex1-config]
verify_jwt = false

[functions.bybit-broker]
verify_jwt = false