project_id = "codhlwjogfjywmjyjbbn"

[functions.bybit-broker]
verify_jwt = false

[functions.aitradex1-strategy-engine]
verify_jwt = false

[functions.live-price-feed]
verify_jwt = false

[functions.unified-signal-engine]
verify_jwt = false

[functions.crypto-scheduler]
verify_jwt = false

[functions.auto-signals-scheduler]
verify_jwt = false

[functions.production-signal-generator]
verify_jwt = false

[functions.debug-trading-status]
verify_jwt = false

[functions.bybit-live-trading]
verify_jwt = false

[functions.telegram-signals]
verify_jwt = false

[functions.enhanced-signal-generation]
verify_jwt = false

[functions.live-scanner-production]
verify_jwt = false

[functions.platform-activation]
verify_jwt = false