project_id = "codhlwjogfjywmjyjbbn"

[functions.aitradex1-enhanced-scanner]
verify_jwt = false

[functions.aitradex1-original-scanner]
verify_jwt = false

[functions.aitradex1-trade-executor]
verify_jwt = false

[functions.automated-trading-orchestrator]
verify_jwt = false

[functions.backtest-engine]
verify_jwt = false

[functions.bybit-authenticate]
verify_jwt = false

[functions.calculate-spynx-scores]
verify_jwt = false

[functions.ccxt-live-feed]
verify_jwt = false

[functions.comprehensive-trading-pipeline]
verify_jwt = false

[functions.crypto-scheduler]
verify_jwt = false

[functions.debug-trading-status]
verify_jwt = false

[functions.diagnostics]
verify_jwt = false

[functions.direct-3commas-test]
verify_jwt = false

[functions.direct-bybit-test]
verify_jwt = false

[functions.enhanced-ccxt-feed]
verify_jwt = false

[functions.enhanced-signal-generation]
verify_jwt = false

[functions.live-data-starter]
verify_jwt = false

[functions.live-exchange-feed]
verify_jwt = false

[functions.live-scanner-production]
verify_jwt = false

[functions.live-signal-orchestrator]
verify_jwt = false

[functions.paper-trading-executor]
verify_jwt = false

[functions.quantum-analysis]
verify_jwt = false

[functions.scanner-engine]
verify_jwt = false

[functions.signals-api]
verify_jwt = false

[functions.automated-trading-executor]
verify_jwt = false

[functions.live-signal-orchestrator]
verify_jwt = false

[functions.system-restart]
verify_jwt = false

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326