project_id = "codhlwjogfjywmjyjbbn"

[functions.aitradex1-enhanced-scanner]
verify_jwt = false

[functions.enhanced-signal-generation]
verify_jwt = false

[functions.live-scanner-production]
verify_jwt = false

[functions.paper-trading-executor]
verify_jwt = false

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326